config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-scg:
      branch: master
      repo: https://github.com/ARGOeu/argo-scg.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-scg git:
        commands:
        - /usr/bin/env sh .sqa/script.harlequin_reserved_turkey.sh
        container: qc.acc_wave_persistent_kookaburra
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-scg find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.banana_fair_shark.sh
        container: qc.doc_powder_restless_wolf
      github.com/ARGOeu/argo-scg git:
        commands:
        - /usr/bin/env sh .sqa/script.ice_spontaneous_tarantula.sh
        container: qc.doc_purple_sad_dolphin
      github.com/ARGOeu/argo-scg markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.walnut_grateful_turtle.sh
        container: qc.doc_fog_zany_finch
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-scg licensee:
        commands:
        - /usr/bin/env sh .sqa/script.powder_helpful_manatee.sh
        container: qc.lic_tundra_flexible_snail
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-scg bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunset_persistent_mandrill.sh
        container: qc.sec_mauve_motivated_parrot
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-scg flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thistle_artistic_narwhal.sh
        container: qc.sty_fandango_bold_hawk
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-scg pytest:
        commands:
        - /usr/bin/env sh .sqa/script.jasmine_artistic_komodo.sh
        container: qc.uni_pink_respectful_beaver
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-scg get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blush_restless_snail.sh
        container: qc.ver_emerald_responsible_camel
timeout: 5400
